// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WEB'),
    appId: '1:543856158845:web:3db5102234a240a541e914',
    messagingSenderId: '543856158845',
    projectId: 'agapay-capstone',
    authDomain: 'agapay-capstone.firebaseapp.com',
    storageBucket: 'agapay-capstone.firebasestorage.app',
    measurementId: 'G-H81BLDEGK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_ANDROID'),
    appId: '1:543856158845:android:79ccbfc7f6c186c241e914',
    messagingSenderId: '543856158845',
    projectId: 'agapay-capstone',
    storageBucket: 'agapay-capstone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_IOS'),
    appId: '1:543856158845:ios:06926218d328a76c41e914',
    messagingSenderId: '543856158845',
    projectId: 'agapay-capstone',
    storageBucket: 'agapay-capstone.firebasestorage.app',
    iosBundleId: 'com.example.agapayUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_MACOS'),
    appId: '1:543856158845:ios:06926218d328a76c41e914',
    messagingSenderId: '543856158845',
    projectId: 'agapay-capstone',
    storageBucket: 'agapay-capstone.firebasestorage.app',
    iosBundleId: 'com.example.agapayUsers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: const String.fromEnvironment('FIREBASE_API_KEY_WINDOWS'),
    appId: '1:543856158845:web:be380d95317803ec41e914',
    messagingSenderId: '543856158845',
    projectId: 'agapay-capstone',
    authDomain: 'agapay-capstone.firebaseapp.com',
    storageBucket: 'agapay-capstone.firebasestorage.app',
    measurementId: 'G-MGS4ZECPJM',
  );
}
